# Generated by Django 4.2 on 2023-04-26 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_accountsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
    ]
