# Generated by Django 4.2 on 2023-04-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Opportunities', '0001_initial'),
        ('Accounts', '0002_alter_accountsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.accountsmodel')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Opportunities.opportunitiesmodel')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
