# Generated by Django 4.2 on 2023-04-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Leads', '0002_remove_leads_id_alter_leads_leads_id'),
        ('Accounts', '0002_alter_accountsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitiesModel',
            fields=[
                ('opportunity_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('stage', models.CharField(max_length=255)),
                ('expected_close_date', models.DateField()),
                ('probability', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.accountsmodel')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leads.leads')),
            ],
            options={
                'verbose_name_plural': 'Oppurtunity',
            },
        ),
    ]
