# Generated by Django 4.2 on 2023-04-26 05:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('billing_address', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('leads_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('company', models.CharField(max_length=255)),
                ('lead_source', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='OpportunitiesModel',
            fields=[
                ('opportunity_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('stage', models.CharField(max_length=255)),
                ('expected_close_date', models.DateField()),
                ('probability', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.accountsmodel')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.leads')),
            ],
            options={
                'verbose_name_plural': 'Oppurtunity',
            },
        ),
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.accountsmodel')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.opportunitiesmodel')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='ReportsModel',
            fields=[
                ('report_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.accountsmodel')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.opportunitiesmodel')),
            ],
            options={
                'verbose_name_plural': 'Report',
            },
        ),
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('note_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('note_text', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.accountsmodel')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.opportunitiesmodel')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
