# Generated by Django 4.2 on 2023-04-26 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='leads',
            name='leads_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
    ]
